/**
 * Domain entity types aligned with the Prisma schema.
 * UI view models remain in feature folders; these are persistence-layer shapes.
 */

import type {
  Agent,
  Building,
  Buyer,
  Community,
  ComparableProperty,
  Deal,
  DealStatus,
  Document,
  FloorPlan,
  Furnishing,
  Lease,
  LeaseStatus,
  Listing,
  ListingStatus,
  MarketStatistics,
  MarketStatisticsPeriod,
  MarketStatisticsScope,
  MasterCommunity,
  Offer,
  OfferStatus,
  Organization,
  Owner,
  Photo,
  PriceHistory,
  Property,
  PropertyNote,
  PropertyStatus,
  PropertyType,
  ListingType,
  Task,
  TaskPriority,
  TaskStatus,
  Tenant,
  User,
  UserRole,
  Video,
  Viewing,
  ViewingStatus,
  ViewType,
} from "@prisma/client";

export type {
  Agent,
  Building,
  Buyer,
  Community,
  ComparableProperty,
  Deal,
  Document,
  FloorPlan,
  Lease,
  Listing,
  MarketStatistics,
  MasterCommunity,
  Offer,
  Organization,
  Owner,
  Photo,
  PriceHistory,
  Property,
  PropertyNote,
  ListingType,
  Task,
  Tenant,
  User,
  DealStatus,
  Furnishing,
  LeaseStatus,
  ListingStatus,
  MarketStatisticsPeriod,
  MarketStatisticsScope,
  OfferStatus,
  PropertyStatus,
  PropertyType,
  TaskPriority,
  TaskStatus,
  UserRole,
  ViewingStatus,
  ViewType,
  Video,
  Viewing,
};

/** Entity identifier used across repositories and services. */
export type EntityId = string;

/** ISO 4217 currency code. */
export type CurrencyCode = string;
